-- MySQL Script generated by MySQL Workbench
-- jue 14 may 2020 14:22:29 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eva_docente
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eva_docente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eva_docente` ;
USE `eva_docente` ;

-- -----------------------------------------------------
-- Table `eva_docente`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva_docente`.`Users` ;

CREATE TABLE IF NOT EXISTS `eva_docente`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `eva_docente`.`Forms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva_docente`.`Forms` ;

CREATE TABLE IF NOT EXISTS `eva_docente`.`Forms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(255) NOT NULL,
  `identification_num` INT NOT NULL,
  `academic_program` VARCHAR(255) NOT NULL,
  `submitter_name` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC),
  UNIQUE INDEX `identification_num_UNIQUE` (`identification_num` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eva_docente`.`Question_Types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva_docente`.`Question_Types` ;

CREATE TABLE IF NOT EXISTS `eva_docente`.`Question_Types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eva_docente`.`Question_Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva_docente`.`Question_Categories` ;

CREATE TABLE IF NOT EXISTS `eva_docente`.`Question_Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eva_docente`.`Questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva_docente`.`Questions` ;

CREATE TABLE IF NOT EXISTS `eva_docente`.`Questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(255) NOT NULL,
  `type` INT NOT NULL,
  `category` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Questions_Question_Types_idx` (`type` ASC),
  INDEX `fk_Questions_Question_Categories1_idx` (`category` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eva_docente`.`Responses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva_docente`.`Responses` ;

CREATE TABLE IF NOT EXISTS `eva_docente`.`Responses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  `id_question` INT NOT NULL,
  `id_form` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Responses_Questions1_idx` (`id_question` ASC),
  INDEX `fk_Responses_Forms1_idx` (`id_form` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eva_docente`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eva_docente`.`Comments` ;

CREATE TABLE IF NOT EXISTS `eva_docente`.`Comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  `id_form` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `value_UNIQUE` (`value` ASC),
  UNIQUE INDEX `id_form_UNIQUE` (`id_form` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `eva_docente`.`Question_Types`
-- -----------------------------------------------------
START TRANSACTION;
USE `eva_docente`;
INSERT INTO `eva_docente`.`Question_Types` (`id`, `value`) VALUES (1, 'multiple_choices');
INSERT INTO `eva_docente`.`Question_Types` (`id`, `value`) VALUES (2, 'text');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eva_docente`.`Question_Categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `eva_docente`;
INSERT INTO `eva_docente`.`Question_Categories` (`id`, `value`) VALUES (1, 'Conocimiento disciplinar');
INSERT INTO `eva_docente`.`Question_Categories` (`id`, `value`) VALUES (2, 'Comunicación');
INSERT INTO `eva_docente`.`Question_Categories` (`id`, `value`) VALUES (3, 'Competencias digitales');
INSERT INTO `eva_docente`.`Question_Categories` (`id`, `value`) VALUES (4, 'Pedagogía y didáctica');
INSERT INTO `eva_docente`.`Question_Categories` (`id`, `value`) VALUES (5, 'Evaluación');
INSERT INTO `eva_docente`.`Question_Categories` (`id`, `value`) VALUES (6, 'Disposición y motivación');

COMMIT;


-- -----------------------------------------------------
-- Data for table `eva_docente`.`Questions`
-- -----------------------------------------------------
START TRANSACTION;
USE `eva_docente`;
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (1, 'En las clases en vivo y tutorías, demuestro un alto conocimiento de los temas del espacio académico.', 1, 1);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (2, 'En las clases en vivo y tutorías, demuestro que estoy actualizado en los temas del espacio académico.', 1, 1);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (3, 'Respondo oportunamente los mensajes, foros, correos electrónicos y demás comunicaciones dentro del espacio académico.', 1, 2);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (4, 'Me comunico de manera clara y respetuosa.', 1, 2);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (5, 'Domino las herramientas de la plataforma para el desarrollo del espacio académico.', 1, 3);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (6, 'Propongo actividades que incentivan el uso de diferentes recursos digitales y herramientas tecnológicas dentro del espacio académico.', 1, 3);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (7, 'Propongo recursos en inglés relacionados con temas del espacio académico.', 1, 3);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (8, 'Explico de manera clara y precisa los temas del espacio académico.', 1, 4);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (9, 'Explico de manera clara y precisa las actividades que se proponen dentro del espacio académico.', 1, 4);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (10, 'Presento los contenidos de manera novedosa y creativa.', 1, 4);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (11, 'Realizo las clases en vivo y las tutorías cumpliendo con los horarios establecidos.', 1, 4);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (12, 'He desarrollado los temas propuestos en la guía didáctica según el cronograma establecido.', 1, 4);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (13, 'He desarrollado los temas propuestos en la guía didáctica según el cronograma establecido.', 1, 5);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (14, 'Socializo la guía didáctica y los criterios de evaluación al iniciar el espacio académico.', 1, 5);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (15, 'Utilizo las rúbricas para evaluar todas las actividades del espacio académico.', 1, 5);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (16, 'Motivo y acompaño a los estudiantes a alcanzar los resultados de aprendizaje esperados.', 1, 6);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (17, 'Genero un ambiente que fomenta la interacción y participación de los estudiantes.', 1, 6);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (18, 'Incentivo a los estudiantes a participar en eventos académicos, exposiciones o espacios culturales que complementan su formación profesional.', 1, 6);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (19, 'Promuevo la investigación formativa a partir estrategias como la indagación, la búsqueda de referentes o los estudios de caso dentro del espacio académico.', 1, 6);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (20, 'Como docente-tutor, ¿cuál es tu principal aporte al mejoramiento de la calidad educativa de la Uvirtual?', 2, 6);
INSERT INTO `eva_docente`.`Questions` (`id`, `value`, `type`, `category`) VALUES (21, '¿Qué oportunidades y recomendaciones consideras que podrían mejorar tu desempeño como docente-tutor de la UVirtual?', 2, 6);

COMMIT;

